"use client";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [mobileRotated, setMobileRotated] = useState(false);
  useEffect(() => {
    const handleResize = () => {
      if ((window.innerWidth >= window.innerHeight) && (window.innerHeight <= 450)) {
        setMobileRotated(true);
      } else {
        setMobileRotated(false);
      }
    };

    handleResize();

    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  useEffect(() => {
    console.log(mobileRotated)
  }, [mobileRotated]);
  
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
